#!/usr/bin/env python3
"""Flashcard decks (C8) built from each lesson's existing [!terms] callout. No new text is written:
front = the bold term, back = the lesson's own one-line definition.

Output: _System/Flashcards/Phase N Flashcards.md (English) and Phase N Flashcards (TH).md (Thai), plus
Phase N Questions.md / (TH).md: every [!check] question with the lesson's own answer (multi-line cards).
Format: `Term::Definition`, one card per line, read by the Obsidian "Spaced Repetition" community plugin
(deck tags #flashcards/en/phase-N and #flashcards/th/phase-N). The files are generated: re-run this script
after editing lessons; don't edit the decks by hand.

Run: python3 _tools/flashcards.py
"""
import json
import re
from pathlib import Path

import sync

ROOT = Path(__file__).resolve().parent.parent
CUR = json.loads((ROOT / "_tools/curriculum.json").read_text(encoding="utf-8"))
OUT = ROOT / "_System/Flashcards"
TERM = re.compile(r"^>\s*[-*]\s+\*\*(.+?)\*\*\s*[—–-]\s*(.+)$")


def split_langs(text):
    text = re.sub(r"^---\n.*?\n---\n", "", text, count=1, flags=re.S)
    en, _, th = text.partition("%% TH %%")
    return {"en": en, "th": th}


def terms(part):
    out, inside = [], False
    for line in part.splitlines():
        if re.match(r"^>\s*\[!terms\]", line):
            inside = True
            continue
        if inside:
            if not line.startswith(">"):
                inside = False
                continue
            m = TERM.match(line)
            if m:
                front, back = m.group(1).strip(), m.group(2).strip()
                if "::" in front + back:
                    continue
                out.append((front, back))
    return out


def checks(part):
    """(question, answer) pairs from every [!check] callout: '> **Q1.** …' followed by a nested '> > [!answer]-' block."""
    out, inside, q, ans, in_ans = [], False, None, [], False

    def flush():
        if q and ans:
            out.append((q, "\n".join(ans)))

    for line in part.splitlines():
        if re.match(r"^>\s*\[!check\]", line):
            flush()
            inside, q, ans, in_ans = True, None, [], False
            continue
        if not inside:
            continue
        if not line.startswith(">"):
            flush()
            inside, q, ans, in_ans = False, None, [], False
            continue
        m = re.match(r"^>\s*\*\*Q\d+\.\*\*\s*(.+)$", line)
        if m:
            flush()
            q, ans, in_ans = m.group(1).strip(), [], False
            continue
        if re.match(r"^>\s*>\s*\[!answer\]", line):
            in_ans = True
            continue
        if in_ans:
            t = re.sub(r"^>\s*>\s?", "", line).strip()
            if t and t != "?":
                ans.append(t)
    flush()
    return out


def write_questions():
    """One deck of self-check questions per phase and language (multi-line cards: question / ? / answer)."""
    total = {"en": 0, "th": 0}
    for ph in CUR["phases"]:
        decks = {"en": [], "th": []}
        for l in ph["lessons"]:
            p = sync.lesson_path(ph, l)
            if not p.exists():
                continue
            parts = split_langs(p.read_text(encoding="utf-8"))
            for lang in ("en", "th"):
                qs = checks(parts[lang])
                if qs:
                    decks[lang].append((p.stem, l["id"], l["en"] if lang == "en" else l["th"], qs))
        for lang, sections in decks.items():
            if not sections:
                continue
            n = sum(len(x) for *_, x in sections)
            total[lang] += n
            if lang == "en":
                name = f"Phase {ph['n']} Questions.md"
                head = (f"#flashcards/en/questions/phase-{ph['n']}\n\n# Phase {ph['n']} self-check questions · {ph['title']['en']}\n\n"
                        f"> [!note]\n> {n} cards: every **Check your understanding** question in this phase, with the lesson's own answer. "
                        f"Generated by `_tools/flashcards.py`; edit the lessons, not this file. Some questions refer to a figure in the lesson: open the lesson link.\n")
            else:
                name = f"Phase {ph['n']} Questions (TH).md"
                head = (f"#flashcards/th/questions/phase-{ph['n']}\n\n# คำถามทบทวนเฟส {ph['n']} · {ph['title']['th']}\n\n"
                        f"> [!note]\n> {n} ใบ: ทุกคำถาม **เช็กความเข้าใจ** ในเฟสนี้ พร้อมคำตอบของบทเรียนเอง "
                        f"สร้างอัตโนมัติด้วย `_tools/flashcards.py` แก้ที่บทเรียน ไม่ใช่ไฟล์นี้ บางคำถามอ้างถึงภาพในบทเรียน: เปิดลิงก์บทเรียน\n")
            body = [head]
            for stem, lid, title, qs in sections:
                body.append(f"\n## {lid} [[{stem}|{title}]]\n")
                for qq, aa in qs:
                    body += [qq, "?", aa, ""]
            (OUT / name).write_text("\n".join(body) + "\n", encoding="utf-8")
    print(f"questions: {total['en']} EN + {total['th']} TH cards → {OUT}")


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    total = {"en": 0, "th": 0}
    for ph in CUR["phases"]:
        decks = {"en": [], "th": []}
        for l in ph["lessons"]:
            p = sync.lesson_path(ph, l)
            if not p.exists():
                continue
            parts = split_langs(p.read_text(encoding="utf-8"))
            for lang in ("en", "th"):
                cards = terms(parts[lang])
                if cards:
                    title = l["en"] if lang == "en" else l["th"]
                    decks[lang].append((p.stem, l["id"], title, cards))
        for lang, sections in decks.items():
            if not sections:
                continue
            n = sum(len(c) for *_, c in sections)
            total[lang] += n
            if lang == "en":
                name = f"Phase {ph['n']} Flashcards.md"
                head = (f"#flashcards/en/phase-{ph['n']}\n\n# Phase {ph['n']} flashcards · {ph['title']['en']}\n\n"
                        f"> [!note]\n> {n} cards made from the **Words you need** box of each lesson. "
                        f"Generated by `_tools/flashcards.py`; edit the lessons, not this file. "
                        f"Use with the *Spaced Repetition* plugin, or cover the right side and test yourself.\n")
            else:
                name = f"Phase {ph['n']} Flashcards (TH).md"
                head = (f"#flashcards/th/phase-{ph['n']}\n\n# บัตรคำเฟส {ph['n']} · {ph['title']['th']}\n\n"
                        f"> [!note]\n> {n} ใบ สร้างจากกล่อง **คำศัพท์ที่ต้องรู้** ของแต่ละบทเรียน "
                        f"สร้างอัตโนมัติด้วย `_tools/flashcards.py` แก้ที่บทเรียน ไม่ใช่ไฟล์นี้ "
                        f"ใช้กับปลั๊กอิน *Spaced Repetition* หรือปิดด้านขวาแล้วทดสอบตัวเอง\n")
            body = [head]
            for stem, lid, title, cards in sections:
                body.append(f"\n## {lid} [[{stem}|{title}]]\n")
                body += [f"{a}::{b}" for a, b in cards]
            (OUT / name).write_text("\n".join(body) + "\n", encoding="utf-8")
    print(f"flashcards: {total['en']} EN + {total['th']} TH cards → {OUT}")
    write_questions()


if __name__ == "__main__":
    main()
