#!/usr/bin/env python3
"""Keep the vault in sync with curriculum.json.
- creates phase folders, phase index notes and lesson stubs (never overwrites)
- regenerates _System/Task Board.md from each lesson's `status`
Run: python3 _tools/sync.py
"""
import json, re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CUR = json.loads((ROOT / "_tools/curriculum.json").read_text(encoding="utf-8"))


def safe(name):
    return re.sub(r'[\\/:*?"<>|]', "-", name)


def lesson_path(phase, lesson):
    return ROOT / phase["folder"] / f"{lesson['id']} {safe(lesson['en'])}.md"


def read_status(p):
    if not p.exists():
        return "missing"
    m = re.search(r"^status:\s*(\w+)", p.read_text(encoding="utf-8"), re.M)
    return m.group(1) if m else "stub"


def stub(phase, lesson):
    return f"""---
id: "{lesson['id']}"
phase: {phase['n']}
status: stub
tags: [phase{phase['n']}]
---
%% EN %%
# {lesson['en']}

> [!todo] Not written yet
> Follow [[Style Guide]]. Part of [[{phase['folder']} - Index]].

%% TH %%
---
# {lesson['th']}

> [!todo] ยังไม่ได้เขียน
"""


def phase_index(phase, prev_p, next_p):
    rows = "\n".join(
        f"| {l['id']} | [[{l['id']} {safe(l['en'])}\\|{l['en']}]] | {l['th']} |" for l in phase["lessons"]
    )
    nav = []
    if prev_p:
        nav.append(f"← [[{prev_p['folder']} - Index|Phase {prev_p['n']}]]")
    nav.append("[[00 Home|Home]]")
    if next_p:
        nav.append(f"[[{next_p['folder']} - Index|Phase {next_p['n']}]] →")
    return f"""---
tags: [phase, phase{phase['n']}]
phase: {phase['n']}
---
# Phase {phase['n']} · {phase['title']['en']}
**{phase['title']['th']}**

> [!mindset] Goal
> {phase['goal']['en']}
> {phase['goal']['th']}

| # | Lesson | บทเรียน |
|---|---|---|
{rows}

{' · '.join(nav)}
"""


def main():
    phases = CUR["phases"]
    board = ["---", "tags: [system]", "---", "# Task Board", "",
             "Generated by `_tools/sync.py` from each lesson's `status`. Do not edit by hand.", ""]
    total = done = 0
    for i, ph in enumerate(phases):
        folder = ROOT / ph["folder"]
        folder.mkdir(exist_ok=True)
        idx = folder / f"{ph['folder']} - Index.md"
        idx.write_text(phase_index(ph, phases[i - 1] if i else None,
                                   phases[i + 1] if i + 1 < len(phases) else None), encoding="utf-8")
        ph_done = 0
        lines = []
        for l in ph["lessons"]:
            p = lesson_path(ph, l)
            if not p.exists():
                p.write_text(stub(ph, l), encoding="utf-8")
            st = read_status(p)
            total += 1
            if st == "done":
                done += 1; ph_done += 1
            box = "x" if st == "done" else " "
            lines.append(f"- [{box}] {l['id']} [[{p.stem}|{l['en']}]] — `{st}`")
        board.append(f"## Phase {ph['n']} · {ph['title']['en']} ({ph_done}/{len(ph['lessons'])})")
        board += lines + [""]
    board.insert(6, f"\n**Progress: {done}/{total} lessons done**\n")
    (ROOT / "_System/Task Board.md").write_text("\n".join(board), encoding="utf-8")
    print(f"synced: {done}/{total} done")


if __name__ == "__main__":
    main()
